
#pragma once

#define SH_SRP_KEYPAIR 1024


#define SH_ERRORCODE_GENRALERROR 1
#define SH_ERRORCODE_SRPERROR 2
#define SH_ERRORCODE_PARSINGFAILED 3
#define SH_ERRORCODE_USERNOTFOUND 4
#define SH_ERRORCODE_AUTHENTICATIONFAILED 5
