
#pragma once

#define SAN2_WAITFORCAPSULE_ERROR 0
#define SAN2_WAITFORCAPSULE_ERROR_INVALID_RESPONSE 1
#define SAN2_WAITFORCAPSULE_ERROR_CAPSULE_UNPACK 2
#define SAN2_WAITFORCAPSULE_SUCCESS 3
#define SAN2_WAITFORCAPSULE_TIMEOUT 4
#define SAN2_WAITFORCAPSULE_ERROR_INVOKE_FAILED 5
